use bevy::prelude::*;

#[derive(Resource)]
pub struct Tuning {
    pub boost_max_speed: f32,
    pub bullet_radius: f32,
    pub bullet_speed: f32,
    pub bullet_lifetime: f32,
    pub camera_view_height: f32,
    pub camera_zoom_base: f32,
    pub camera_lookahead: f32,
    pub camera_lookahead_max: f32,
    pub camera_zoom_max: f32,
    pub camera_zoom_lambda: f32,
    pub camera_follow_lambda: f32,
    pub drag: f32,
    pub fire_cooldown: f32,
    pub max_speed: f32,
    pub playfield: Vec2,
    pub shake_max_offset: f32,
    pub ship_radius: f32,
    pub thrust: f32,
    pub thrust_forward: f32,
    pub thrust_strafe: f32,
    pub thrust_reverse: f32,
    pub drag_base: f32,
    pub brake_multiplier: f32,
    pub max_bank: f32,
    pub bank_rate: f32,
    pub bank_squash: f32,
    pub trauma_decay: f32,
    pub turn_rate: f32,
}

impl Default for Tuning {
    fn default() -> Self {
        Self {
            playfield: Vec2::new(1280.0, 720.0),
            ship_radius: 12.0,
            thrust: 380.0,
            turn_rate: 3.6,
            drag: 0.6,
            bullet_radius: 2.5,
            bullet_speed: 620.0,
            bullet_lifetime: 2.1,
            fire_cooldown: 0.09,
            camera_view_height: 720.0,
            camera_zoom_base: 1.0,
            trauma_decay: 1.4,
            camera_lookahead: 0.35,
            camera_lookahead_max: 260.0,
            boost_max_speed: 900.0,
            camera_zoom_max: 1.35,
            camera_zoom_lambda: 3.0,
            camera_follow_lambda: 6.0,
            shake_max_offset: 18.0,
            thrust_forward: 900.0,
            thrust_strafe: 420.0,
            thrust_reverse: 350.0,
            drag_base: 0.18,
            brake_multiplier: 9.0,
            max_speed: 700.0,
            max_bank: 0.35,
            bank_rate: 8.0,
            bank_squash: 0.4,
        }
    }
}
